version: '3.6'
services:
  composer:
    image: 'composer:1.8'
    command: install
    volumes:
      - './:/app'

  phpApache:
    image: 'php:apache'
    ports:
      - '8081:80'
    volumes:
      - './:/var/www/html'